#SPDX-License-Identifier: MIT-0
---
- name: Disable SELinux on RedHat-based systems
  selinux:
    state: disabled
  when: ansible_os_family == "RedHat"

- name: Stop and disable firewalld (RedHat-based)
  service:
    name: firewalld
    state: stopped
    enabled: no
  when: ansible_os_family == "RedHat"
  ignore_errors: yes

- name: Stop and disable UFW (Debian-based)
  service:
    name: ufw
    state: stopped
    enabled: no
  when: ansible_os_family == "Debian"
  ignore_errors: yes

# tasks file for roles/common
